version: '3'
services:
  db:
    ports:
       - 25432:5432
    image: postgres:15.1-alpine
    # volumes:
    #   - ./:/home/sql:rw
    environment:
      POSTGRES_PASSWORD: supersecret
    # command: bash -c "~/setup-db.sh"

  proxy:
    network_mode: "host"
    build: ./
    ports:
      - 80:80
      - 443:443
